### ISSUE TITLE
Clockify Workspace ( Time Tracker )

### ISSUE THREAD

**Issue by PratikMate** [PratikMate/handy-string-7765#12]
- [x] Top Section
- [x] Project Input Bar
- [x] Timer
- [x] Add button
- [x] Project List section
- [x] Total time at top of project list
- [x] Resume time button in each project item
