### ISSUE TITLE
Clockify Workspace ( Time Tracker ) Backend

### ISSUE THREAD

**Issue by PratikMate** [PratikMate/handy-string-7765#14]
- [x] Different routes for each user
- [x] Adding data of each user 
- [x] Multiple key for storing data 
- [x] CRUD operations
